#! /bin/sh
if test -f "asmCode.s"; then
    rm asmCode.s
fi
if test -f "asmCode.o"; then
    rm asmCode.o
fi

fileName=$1
Compiler/AutoGeneratedFiles/a.out < $fileName
if test -f "asmCode.s"; then
    as -o asmCode.o asmCode.s
    ld -o ${fileName%.*}.out asmCode.o
    rm asmCode.o
    mv asmCode.s ${fileName%.*}.s
fi
