#! /bin/sh
cd Compiler
bison -d -y Parser.y
flex Scanner.l
gcc y.tab.c lex.yy.c Tree.c Main.c SymbolCollection.c TypeChecking.c IntermediateCodeGeneration.c Peephole.c Emit.c
mv a.out AutoGeneratedFiles/a.out
mv lex.yy.c AutoGeneratedFiles/lex.yy.c
mv y.tab.c AutoGeneratedFiles/y.tab.c
mv y.tab.h AutoGeneratedFiles/y.tab.h
