FlexBison\bison -d -y Compiler\Parser.y
FlexBison\flex Compiler\Scanner.l
gcc Compiler\Tree.h y.tab.c lex.yy.c Compiler\Tree.c Compiler\main.c Compiler\SymbolCollection.c Compiler\TypeChecking.c Compiler\DebugUtils.c Compiler\IntermediateCodeGeneration.c
@move a.exe Compiler\AutoGeneratedFiles\a.exe
@move lex.yy.c Compiler\AutoGeneratedFiles\lex.yy.c
@move y.tab.c Compiler\AutoGeneratedFiles\y.tab.c
@move y.tab.h Compiler\AutoGeneratedFiles\y.tab.h
@del Compiler\Tree.h.gch