@echo off
REM @Compiler\AutoGeneratedFiles\a < Example\example.txt

REM @Compiler\AutoGeneratedFiles\a < Example\example.txt
REM Compiler\AutoGeneratedFiles\a < Example\leastCoercionTest.txt
@Compiler\AutoGeneratedFiles\a < Example\return.txt